# Generated by Django 5.0.3 on 2024-05-15 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_employee_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RenameField(
            model_name='itasset',
            old_name='asset_id',
            new_name='asset_tag',
        ),
        migrations.RenameField(
            model_name='itasset',
            old_name='status',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='image',
        ),
        migrations.AddField(
            model_name='itasset',
            name='deployed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
