# Generated by Django 5.0.3 on 2024-05-15 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_category_rename_asset_id_itasset_asset_tag_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ITAsset',
        ),
    ]
