# Generated by Django 5.0.3 on 2024-04-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=100, unique=True)),
                ('asset_type', models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Printer', 'Printer'), ('Server', 'Server'), ('Networking', 'Networking'), ('Other', 'Other')], max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='birth_date',
            new_name='hire_date',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='last_name',
            new_name='reports_to',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='is_active',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='middle_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
    ]
