# Generated by Django 5.0.3 on 2024-04-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_itasset_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='itasset',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itasset',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='asset_type',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Headset', 'Headset'), ('Printer', 'Printer'), ('Server', 'Server'), ('Networking', 'Networking'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='status',
            field=models.CharField(choices=[('In stock', 'In stock'), ('In transit', 'In transit'), ('In use', 'In use'), ('In maintenance', 'In maintenance'), ('Retired', 'Retired'), ('Missing', 'Missing'), ('Duplicate', 'Duplicate')], max_length=100),
        ),
    ]
