# Generated by Django 5.0.3 on 2024-04-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_itasset_featured_itasset_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Voluntary', 'Voluntary'), ('Supended', 'Suspended'), ('Terminated', 'Terminated')], max_length=100),
        ),
    ]
