# Generated by Django 5.0.3 on 2024-05-14 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_employee_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itasset',
            name='featured',
        ),
    ]
