# Generated by Django 5.0.3 on 2024-05-15 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_itasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=100, unique=True)),
                ('asset_type', models.CharField(choices=[('Laptop', 'Laptop'), ('Desktop', 'Desktop'), ('Headset', 'Headset'), ('Printer', 'Printer'), ('Server', 'Server'), ('Networking', 'Networking'), ('Other', 'Other')], max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('In stock', 'In stock'), ('In transit', 'In transit'), ('In use', 'In use'), ('In maintenance', 'In maintenance'), ('Retired', 'Retired'), ('Missing', 'Missing'), ('Duplicate', 'Duplicate')], max_length=100)),
                ('deployed_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.employee')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
