# Generated by Django 5.0.3 on 2024-05-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_itasset_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Resigned', 'Resigned'), ('Supended', 'Suspended'), ('Terminated', 'Terminated')], max_length=100),
        ),
    ]
